# Generated by Django 3.0.5 on 2020-04-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsTravello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destiny',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
