# Generated by Django 3.0.5 on 2020-04-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsTravello', '0002_destiny_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destiny',
            old_name='image',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='destiny',
            name='description',
            field=models.TextField(verbose_name=100),
        ),
        migrations.AlterField(
            model_name='destiny',
            name='price',
            field=models.IntegerField(verbose_name=5),
        ),
    ]
